### ISSUE TITLE
Getting error on npm start

### ISSUE THREAD

**Issue by parth-gudhka** [milanvadher/quiz-gateway#3]
This is the error I get @milanvadher. 
I followed the following steps:
```
npm install
npm start
```

`Connected to DB Successfully !! 
{ MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/parthgudhka/code/quiz-gateway/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Pool.EventEmitter.emit (domain.js:441:20)
    at Connection.<anonymous> (/Users/parthgudhka/code/quiz-gateway/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:441:20)
    at Socket.<anonymous> (/Users/parthgudhka/code/quiz-gateway/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! couch_restify@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the couch_restify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/parthgudhka/.npm/_logs/2019-01-15T13_29_14_876Z-debug.log`

**Comment by gauravsur** [comment]
It seems you need to install MongoDB
